version: "3.7"
services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://admin:admin@postgres/notes
    ports:
      - "3000:3000"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notes
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080