version: "3.7"
services:
  app:
    build: .
    env_file: .env
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: redis
    ports:
      - "3000:3000"
  redis:
    image: redis:alpine
    ports:
      - "6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]